### ISSUE TITLE
部署完成，但是连不上...

### ISSUE THREAD

**Issue by darktitty** [lisaac/openwrt-in-docker#1]
![photo_2019-06-13_10-40-45](https://user-images.githubusercontent.com/42826254/59402227-064e0080-8dd0-11e9-85f2-d531ed265f28.jpg)
**### 大佬~按照教程在vmware ubuntu中部署完成, 但就是无法连接打开页面是什么原因啊?求解答,谢谢~**

**Comment by darktitty** [comment]
**尝试了很久, 还是不行...**

**Comment by lisaac** [comment]
请给出具体的拓扑结构，以及 docker 中 openwrt 的配置

**Comment by darktitty** [comment]
目前是vmware虚拟机上搞的，有点复杂。电脑网络是192.168.8.206，网关是192.168.8.1，我只按单LAN口设置的。虚拟机上Ubuntu网络是NAT模式，ip是192.168.58.130。是不是我换成桥接来搞好一些？
![TIM图片20190613142516](https://user-images.githubusercontent.com/42826254/59408652-18876900-8de7-11e9-8ebd-30a246862b28.png)

**Comment by darktitty** [comment]
好了 用桥接解决了~
