### ISSUE TITLE
大佬 如果三网口主路由模式怎么搞

### ISSUE THREAD

**Issue by TSL-Johnson** [lisaac/openwrt-in-docker#10]
如题 有三个网口，想要用docker实现openwrt主路由模式，宿主机也通过这个openwrt主路由联网。宿主机直通光猫DHCP获取IP地址，光猫网段：192.168.1.0/24 宿主机后有一个硬路由ap和几个联网设备。

**Comment by lisaac** [comment]
这个项目就是解决这个问题，请仔细阅读Readme和其他issue

**Comment by TSL-Johnson** [comment]
设置容器后wan口正常获取IP，网络诊断正常ping通。lan口dhcp运行正常，下游设备正常获取IP，但不能联网。宿主机系统debian10，网口间没有设置iptables转发，docker 创建macvlan后ip a在系统中看不到macvlan端口，openwrt使用的是esir的buddha docker镜像。（ps：因为不知道是不是设置不同网段就没有在lan口增加网口）大佬可知什么原因。

**Comment by lisaac** [comment]
请提供具体信息

**Comment by 70599** [comment]
@lisaac 
> 这个项目就是解决这个问题，请仔细阅读Readme和其他issue

**本项目docker中的openwrt是主路由的话，可否帮忙看下我对README的如下理解是否有误：**
1. `macvWan`中配置的网关`--gateway=192.168.254.1`是光猫的地址
2. `macvLan`中配置的网关`--gateway=10.1.1.1`是局域网内主路由（容器内openwrt？）的地址，也是局域网内客户端的DNS服务器
3. `macvLan`中配置的子网`--subnet=10.1.1.0/24`是局域网内各客户端从容器内openwrt DHCP服务获取IP的地址池
4. 容器内openwrt网络设置`/etc/config/network`中的`option ipaddr '10.1.1.254'`是openwrt在局域网中作为主路由的IP地址，以后局域网内客户端可以通过这个IP连入SSH，或网页端对openwrt进行管理
5. 光猫是容器内openwrt的网关，容器内openwrt是局域网内所有客户端（包括宿主机）的网关

**我不明白的地方：**
1. [宿主机出口](https://github.com/lisaac/openwrt-in-docker/blob/fd65e91e3b3b774c76cfcbd29e7a40d5ede5101f/README.md?plain=1#L89)章节中[第89行](https://github.com/lisaac/openwrt-in-docker/blob/fd65e91e3b3b774c76cfcbd29e7a40d5ede5101f/README.md?plain=1#L89)和[第104行](https://github.com/lisaac/openwrt-in-docker/blob/fd65e91e3b3b774c76cfcbd29e7a40d5ede5101f/README.md?plain=1#L104)看起来是同样功能的命令，但是用到了不同的IP地址（`10.1.1.2/24`vs`10.1.1.250/24`），有什么特别的原因吗？
2. ↑同一章节[第92行](https://github.com/lisaac/openwrt-in-docker/blob/fd65e91e3b3b774c76cfcbd29e7a40d5ede5101f/README.md?plain=1#L92)和[第108行](https://github.com/lisaac/openwrt-in-docker/blob/fd65e91e3b3b774c76cfcbd29e7a40d5ede5101f/README.md?plain=1#L108)也是看起来同样的功能，用到了不同的IP地址（`10.1.1.254`vs`10.1.1.1`），同问有什么特别的原因吗？
3. `10.1.1.254`和`10.1.1.1`哪一个是本项目环境中局域网内客户端访问容器内openwrt的IP地址？

我在网上找同类资讯尝试了好几次一直没有成功，直到看到本项目。
我仔细阅读了本项目的README，但是这次想在操作之前先搞明白原理。
还烦请多指教，谢谢。

**Comment by lisaac** [comment]
> 
1、如果是做宽带拨号的话，设置 `macWan` 的`gateway`意义不大
2、`macvLan`中的`gateway`的设置，其中本案例中，应该统一设置为10.1.1.254，当时写的比较潦草，每仔细检查，这个设置只是`连接到这个docker network的容器`的默认设置，如果容器有权限的话，是可以修改的。
3、对
4、对
5、可以这样理解

关于宿主机出口章节，其实`使用 ip 命令`和`debian 中可以编辑`是两个平行的步骤，取其一就行，至于ip地址，选其一就行，没有特殊意义。

另外，介于 `openwrt-in-docker` 在高权限运行，有时候会对宿主网络产生影响，已经不建议使用了。
如果需要 luci 管理容器，包括管理其他容器的配置文件，建议移步：[lisaac/luci-in-docker](https://github.com/lisaac/luci-in-docker) （WIP）

**Comment by 70599** [comment]
感谢回复。

我的宿主机是双网口的NanoPi R4S，目前作为主路由正在直接运行openwrt + docker。
不知道是不是R4S特殊，每次在更新openwrt重启后，配置文件都会有一部分缺失（root的密码会被重置，和其他若干）。
这种情况需要再恢复一次备份文件才能正常。

我又比较爱更新（就是能折腾），所以每次更新都操作复杂断网时间比较久，就打算把OS换成Armbian，把openwrt也放进docker运行，每次更新openwrt的rootfs.tar.gz就行了。

折腾了一段时间，很多方案都有各种奇奇怪怪的毛病，openwrt作为总网关，每次更新、重启容器的时候宿主机都会停止响应一段时间甚至彻底失联，体验极为痛苦。

既然大佬也说不建议使用，那我就放弃了，继续现在的openwrt + docker环境。

我倒是没有luci管理容器的需求，更习惯docker-compose管理docker。

还有大佬博客里的[同名文章](https://blog.ick.im/#/posts/4)似乎比这个仓库里的README更新一些？
我再折腾的话是不是看博文更好？

**Comment by lisaac** [comment]
据我了解并非r4s特殊，大概率是固件作者在更新完之后的初始化导致的配置文件重置。

至于op运行于容器，本来就是曲线救国，op一开始就没想过会被跑在容器中……所以会出现各种奇奇怪怪的问题。

另外如果出口带宽不超过500m的话可以考虑作为旁路网关使用，更新就不会断网了

最后，blog和仓库基本都一样……
