### ISSUE TITLE
关于    --privileged参数占用前台的问题

### ISSUE THREAD

**Issue by wangchang54** [lisaac/openwrt-in-docker#3]
你好，我在新建容器时使用    --privileged 参数后，他会把我的前台输出会被占用，无法正常输入，但是不加    --privileged参数，openwrt会有异常，比如打不开luci的接口页面。
请问有什么办法可以阻止这种事情发生吗？谢谢

**Comment by lisaac** [comment]
感觉不是 --privileged 参数问题，应该是 -d 后台运行没加的缘故吧？

**Comment by wangchang54** [comment]
-d参数是存在的，当我加入privileged后无法输入，移除后恢复正常，别的参数并没有变，您还有别的头绪吗？

**Comment by lisaac** [comment]
没有碰到过这种情况，建议排查下镜像，可以尝试使用其他镜像（ubuntu alpine）加此参数是或否有问题？

**Comment by cdllqos** [comment]
@wangchang54 我这边也有这样的情况，请问你解决了吗
