### ISSUE TITLE
为何要打开混杂模式

### ISSUE THREAD

**Issue by flyhigao** [lisaac/openwrt-in-docker#6]
没有必要啊

**Comment by coderhwz** [comment]
为啥没必要啊，老铁，直接用host网络吗？

**Comment by flyhigao** [comment]
哦,我调研过了.
vmware或者kvm中,需要设置混杂模式.
在物理机架构时,不必要.

**Comment by lisaac** [comment]
@flyhigao 
> Your networking equipment needs to be able to handle “promiscuous mode”, where one physical interface can be assigned multiple MAC addresses.
> https://docs.docker.com/network/macvlan/

**Comment by coderhwz** [comment]
我想试一下 host 模式，不知道到时候宿住机怎么连接到openwrt的网络中 ？  求指定 @lisaac
