### ISSUE TITLE
部署完毕Docker无网络

### ISSUE THREAD

**Issue by 5high** [lisaac/openwrt-in-docker#7]
能从ROS路由器里看到有DHCP请求状态是offered，无法ping通。

硬件是树莓派，系统是aarch64。
下面是创建docker的macvlan网络的命令

docker network create -d macvlan \
    --subnet=10.10.10.0/24 --gateway=10.10.10.252 \
    --ipv6 --subnet=fe80::/16 --gateway=fe80::1 \
    -o parent=wlan0 \
    -o macvlan_mode=bridge \
    macvlan

**Comment by lisaac** [comment]
无线网卡是无法使用 macvlan 的
可以考虑使用下 ipvlan 但没有经过测试，如果有结果，请 po 一下

**Comment by 5high** [comment]
多谢回复，我试试看ipvlan有结果发上来。

**Comment by 5high** [comment]
经过测试ipvlan无法正常使用，不知道是不是我自己能力有限。
